dOrgTech/DAOcreator

src/AppState.ts
src/components/DaoCreator/ConfigurationStep/index.tsx
src/components/DaoCreator/FoundersStep.tsx
src/components/DaoCreator/NamingStep.tsx
src/components/DaoCreator/ReviewStep.tsx
src/components/DaoCreator/index.tsx
src/lib/formValidation.ts
src/redux/actions/daoCreator.ts
src/redux/actions/internal/index.ts
src/redux/reducers/daoCreator.ts

The validation is functional. However, I am getting a strange taste of some kind of pasta in my mouth while looking at it.
Reviewers, please help me!
Closes #12

Validation

---

src/components/DaoCreator/index.tsx
src/lib/integrations/daoStack/arc/index.ts
src/lib/integrations/web3/index.ts
src/lib/integrations/web3/typeValidation.ts
src/redux/actions/daoCreator.ts

This will request access and check for Web3 compatibility in the start of the DAOcreator (instead of getting an error in the deployment step if Web3 is not available)

Request access to user accounts. Closes #41

---

src/components/DaoCreator/ReviewStep.tsx

Fixes: https://github.com/dOrgTech/dOrg/issues/36

Pie Charts In Review Step

---

src/lib/integrations/daoStack/arc/contractAddresses.json
src/lib/integrations/daoStack/arc/index.ts
src/lib/integrations/daoStack/arc/schemes.ts
src/lib/integrations/daoStack/arc/typeConversions.ts

I think it would be good to add this into dev and use this as the base when removing the dependence on arc.js ++

Main net support (once upon a time)

---

npm-shrinkwrap.json
src/components/pages/DAOcreator/FeatureStep.tsx
src/components/pages/DAOcreator/SchemeStep.tsx
src/components/pages/DAOcreator/index.tsx
src/lib/integrations/daoStack/arc/schemes.ts

This PR closes: #73 && #69 
Adding a new issue to handle form validation for each of the `FeatureStep` components, and to create a new design for this page. #75

create scheme view / fix stepper

---

npm-shrinkwrap.json
package.json
src/components/App.tsx
src/components/common/Notifications.tsx
src/lib/integrations/daoStack/arc/index.ts
src/redux/actions/daoCreator.ts
src/redux/actions/events/index.ts
src/redux/actions/notifications.ts
src/redux/reducers/notifications.ts
src/state.ts

FYI: Material-UI only supports showing one notification at a time (Material Design Guidelines). This solution uses the library uses [notistack](https://github.com/iamhosseindhv/notistack) which is recommended in the Material-UI documentation for this displaying multiple notifications at once.
closes #37
closes #82

Support for multiple notifications ++

---

src/components/pages/DAOcreator/SchemesStep/index.tsx
src/redux/actions/daoCreator.ts
src/redux/actions/events/index.ts
src/redux/reducers/daoCreator.ts
src/state.ts

User can remove schemes

---

npm-shrinkwrap.json
src/components/pages/DAOcreator/ReviewStep.tsx
src/components/pages/DAOcreator/SchemesStep/AddSchemeDialog.tsx
src/components/pages/DAOcreator/SchemesStep/index.tsx
src/lib/integrations/daoStack/arc/createDao.ts
src/lib/integrations/daoStack/arc/index.ts
src/lib/integrations/daoStack/arc/schemes.ts
src/lib/integrations/daoStack/arc/types.ts
src/lib/integrations/daoStack/arc/votingMachines.ts
src/redux/actions/daoCreator.ts
src/redux/actions/events/index.ts
src/redux/reducers/daoCreator.ts
src/state.ts

Allow users to update scheme params

---

src/components/pages/DAOcreator/FoundersStep.tsx
src/components/pages/DAOcreator/NamingStep.tsx
src/components/pages/DAOcreator/SchemesStep/AddSchemeDialog.tsx
src/lib/integrations/daoStack/arc/votingMachines.ts
src/redux/reducers/daoCreator.ts

add descriptions, fix stepper, spelling

---

npm-shrinkwrap.json
src/lib/integrations/daoStack/arc/schemes.ts

Add generic scheme

---

src/components/pages/DAOcreator/SchemesStep/AddSchemeDialog.tsx
src/components/pages/DAOcreator/SchemesStep/index.tsx
src/lib/integrations/daoStack/arc/schemes.ts
src/lib/integrations/daoStack/arc/types.ts

Specify what schemes can have multiple instances on a DAO

---

npm-shrinkwrap.json
package.json
src/components/common/Notifications.tsx
src/lib/integrations/web3/index.ts

Notifications can be dismissed + Can switch eth account

---

src/lib/integrations/daoStack/arc/votingMachines.ts

Add support for Quorum Vote

---

src/components/pages/DAOcreator/SchemesStep/AddSchemeDialog.tsx
src/lib/integrations/daoStack/arc/createDao.ts
src/lib/integrations/daoStack/arc/schemes.ts

- Make it possible to use the avatar as beneficiary.
- Make it possible to use the DAO's native token as the payment token.
Closes #98

Can now use the parameterize OrganizationRegister with beneficiary and token from the DAO

---

src/components/App.tsx

Fixing Direct Links

---

src/lib/integrations/daoStack/arc/createDao.ts
src/lib/integrations/web3/index.ts

I think most of the issues that people are experiencing on main net is due to transactions timing out and even transactions being dropped (due to low gas price). This should at least help with the timeout problem.

More robust deployment

---

src/components/common/dao/MembersEditor.tsx
src/components/pages/DAOcreator/MembersStep.tsx

Added scroll view to members

---

npm-shrinkwrap.json
package.json
src/components/common/dao/MembersSaveLoad.tsx
src/components/common/dao/MigrationParamsImport.tsx
src/components/common/dao/Migrator/LogLineTypes.ts
src/components/common/dao/Migrator/index.tsx
src/components/common/dao/SchemesEditor.tsx
src/components/pages/DAOcreator/DeployStep.tsx
src/components/pages/DAOcreator/LiveDao.tsx
src/lib/dependency/arc/index.ts
src/lib/dependency/arc/migration.ts
src/lib/dependency/arc/types/index.ts
src/lib/dependency/arc/types/migration.ts
src/lib/dependency/arc/types/schemes.ts
src/lib/dependency/arc/types/votingMachines.ts
src/lib/dependency/web3/index.ts
src/lib/state/DAOcreator.ts
test/dao-params/dao-params-test-1.json
test/dao-params/dao-params-test-2.json
test/dao-params/dao-params-test-3.json

* DAO migration testing
* rinkeby working
* remove param link
* start of migration view
* deployer functional
* almost there
* new test DAO
* updates
* warnings
* Removing warning for CI to pass

Deployment (#201)

---

npm-shrinkwrap.json
src/components/common/dao/MembersEditor.tsx
src/lib/forms/dao/MemberForm.ts
src/lib/forms/validators.ts

Updates based on this original fork PR: https://github.com/dOrgTech/DAOcreator/pull/224

Namesty issue 214 tokens reputation not zero

---

packages/ui_v2/package.json
packages/ui_v2/src/components/DAOcreatorV2/NamingStep.tsx
packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/commonV2/dao/DAOConfigEditor.tsx

This pr is for issue: https://github.com/dOrgTech/DAOcreator/issues/260

[WIP] Issue 260 Cotary Create: Implement functional Step 1

---

packages/ui_v2/package.json
packages/ui_v2/src/components/DAOcreatorV2/SchemesStep.tsx
packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/commonV2/dao/SchemeEditor.tsx
packages/ui_v2/yarn.lock

[WIP] Issue 261 Cotary Create: Implement functional Step 2

---

packages/ui_v2/package.json
packages/ui_v2/src/components/DAOcreatorV2/MembersStep.tsx
packages/ui_v2/src/components/commonV2/FormField/index.tsx
packages/ui_v2/src/components/commonV2/MembersEditorV.tsx
packages/ui_v2/src/util/hooks/forceUpdate.hook.ts
packages/ui_v2/src/util/hooks/index.ts
packages/ui_v2/src/util/index.ts
packages/ui_v2/src/util/truncateString.ts

This pr is for issue: https://github.com/dOrgTech/DAOcreator/issues/262

[WIP] Issue 262 Cotary Create: Implement functional Step 3

---

packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/commonV2/FormField/index.tsx
packages/ui_v2/src/components/commonV2/Stepper.tsx

Adding error message and validation

---

packages/ui_v2/src/components/DAOcreatorV2/InstallStep.tsx
packages/ui_v2/src/components/DAOcreatorV2/NamingStep.tsx
packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/commonV2/Accordion.tsx

Cotary Create: Stepper improvement

---

packages/ui_v2/src/components/commonV2/dao/Migrator/OrganisationLine.tsx
packages/ui_v2/src/components/commonV2/dao/Migrator/index.tsx

Improved error rendering on Step 4 #268

---

packages/ui_v2/package.json
packages/ui_v2/src/components/commonV2/dao/Members/MembersTable.tsx

This PR is for issue: https://github.com/dOrgTech/DAOcreator/issues/296

Cotary Create: Removed unneeded packages and removed old icons library

---

packages/ui_v2/src/components/DAOcreatorV2/SchemesStep.tsx
packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/commonV2/Stepper/UtilityButton.tsx
packages/ui_v2/src/components/commonV2/Stepper/index.tsx
packages/ui_v2/src/components/commonV2/dao/Schemes/AdvanceSchemeEditor.tsx
packages/ui_v2/src/components/commonV2/dao/Schemes/SchemeEditor.tsx
packages/ui_v2/src/components/commonV2/dao/Schemes/Toggle.tsx

Cotary Create: Advance configuration improvement & fix

---

packages/ui_v2/src/components/commonV2/FormField/index.tsx
packages/ui_v2/src/components/commonV2/dao/DAOConfigEditor.tsx

This pr is for issue: https://github.com/dOrgTech/DAOcreator/issues/300

Cotary Create: tabbing issue

---

packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/commonV2/Stepper/index.tsx

This pr is for issues: #303 and #276

Cotary Create: Stepper Preview fixes.

---

packages/ui_v2/src/components/commonV2/dao/Migrator/index.tsx

Cotary Create: Add redeploy button

---

packages/ui_v2/src/components/DAOcreatorV2/index.tsx

Cotary Create: Changed pointer over import/export config

---

packages/ui_v2/src/components/commonV2/FormField/index.tsx
packages/ui_v2/src/components/commonV2/dao/Schemes/AdvanceSchemeEditor.tsx

Issue 307 show hours label advance config

---

packages/ui_v2/package.json
packages/ui_v2/src/components/DAOcreatorV2/SchemesStep.tsx
yarn.lock

Cotary Create: Removed chakra-ui

---

packages/ui_v2/src/components/DAOcreatorV2/SchemesStep.tsx
packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/commonV2/Stepper/ImporterModal.tsx
packages/ui_v2/src/components/commonV2/Stepper/UtilityButton.tsx
packages/ui_v2/src/components/commonV2/Stepper/index.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersAnalytics.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersEditor.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersTable.tsx

Cotary Create: Handled all the compiler warnings with minimal refactoring

---

packages/ui_v2/src/components/DAOcreatorV2/MembersStep.tsx

Cotary Create: Fixed capitalisation on Set Members button #338

---

packages/ui_v2/src/components/commonV2/LineGraphic.tsx

Cotary Create: Fixed line component corner styling #341

---

packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/commonV2/Stepper/index.tsx

Cotary Create: Added enter functionality

---

packages/ui_v2/src/components/commonV2/dao/Members/MemberEditor.tsx

Cotary Create: Added hitting enter to add new member

---

packages/ui_v2/src/components/commonV2/dao/Members/MembersTable.tsx

Cotary Create: Added enter functionality for member editing #348

---

packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/commonV2/Stepper/index.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersEditor.tsx
packages/ui_v2/src/components/commonV2/dao/Schemes/SchemeEditor.tsx
packages/ui_v2/src/components/commonV2/dao/Schemes/Toggle.tsx

Cotary Create: Naming and tooltips

---

packages/ui_v2/src/components/DAOcreatorV2/MembersStep.tsx
packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/web3/core.ts

Cotary Create: Improving MetaMask UX #375

---

packages/ui_v2/src/components/commonV2/Stepper/index.tsx

Cotary Create: Stepper step count styling #353

---

packages/ui_v2/src/components/DAOcreatorV2/MembersStep.tsx
packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersAnalytics.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersEditor.tsx
packages/ui_v2/src/components/web3/core.ts

Cotary Create: Refactored step 3 #368

---

packages/ui_v2/src/components/commonV2/dao/Members/MembersAnalytics.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersEditor.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersTable.tsx

Cotary Create: Merging feedback into its branch

---

packages/ui_v2/src/components/commonV2/dao/Migrator/OrganisationLine.tsx

Cotary Create: Step 4 styling #305

---

packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/commonV2/Stepper/index.tsx

Cotary Create: Handling step 1 feedback #369

---

packages/ui_v2/src/components/DAOcreatorV2/MembersStep.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MemberEditor.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersAnalytics.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersEditor.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersTable.tsx

Cotary Create: Step 3 Feedback #368 

---

packages/ui_v2/src/components/DAOcreatorV2/InstallStep.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersTable.tsx
packages/ui_v2/src/components/commonV2/dao/Migrator/index.tsx

Cotary Create: Handling step 4 feedback #376

---

packages/ui_v2/src/components/DAOcreatorV2/InstallStep.tsx
packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/commonV2/Stepper/index.tsx

Cotary Create: Disabling edits during deployment #391

---

packages/lib/src/forms/dao/DAOConfigForm.ts
packages/lib/src/forms/dao/schemes/ContributionRewardForm.ts
packages/lib/src/forms/dao/schemes/SchemeRegistrarForm.ts
packages/lib/src/forms/validators.ts

Cotary Create: Copy for tooltips changes for lib

---

packages/lib/src/forms/dao/GenesisProtocolForm.ts
packages/lib/src/forms/validators.ts

Closes: https://github.com/dOrgTech/DAOcreator/issues/284

Genesis Protocol Params Fix

---

packages/ui_v2/src/components/commonV2/dao/Schemes/AdvancedEditor.tsx
packages/ui_v2/src/components/commonV2/dao/Schemes/SchemeEditor.tsx

Cotary Create: Update speed buttons

---

packages/ui_v2/src/components/commonV2/dao/Schemes/SchemeEditor.tsx
packages/ui_v2/src/components/utils/schemesUtils.ts

Cotary Create: Fixing auto-incentivize proposal #414

---

packages/ui_v2/src/components/commonV2/dao/Schemes/SchemeEditor.tsx

Cotary Create: Updates SchemeEditor state when form is loaded from localStorage #421

---

package.json
packages/lib/src/forms/dao/GenesisProtocolForm.ts
packages/ui_v1/src/components/common/dao/GenesisProtocolPresetEditor.tsx
packages/ui_v2/src/components/commonV2/dao/Schemes/AdvancedEditor.tsx

Closes: https://github.com/dOrgTech/DAOcreator/issues/415

BoostedVotePeriodLimit >= QuiteEndingPeriod Validation

---

packages/ui_v2/src/components/commonV2/FormField/index.tsx

Added padding to input field for blockie

---

packages/ui_v2/src/components/DAOcreatorV2/InstallStep.tsx
packages/ui_v2/src/components/DAOcreatorV2/MembersStep.tsx
packages/ui_v2/src/components/commonV2/LineGraphic.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersAnalytics.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersTable.tsx
packages/ui_v2/src/components/commonV2/dao/Migrator/OrganizationLine.tsx
packages/ui_v2/src/components/commonV2/dao/Migrator/index.tsx
packages/ui_v2/src/components/commonV2/dao/Schemes/Toggle.tsx

 Cotary Create: Adding copy functionality for dao addresses and logs #416

---

packages/ui_v2/src/components/DAOcreatorV2/NamingStep.tsx
packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/commonV2/FormField/index.tsx
packages/ui_v2/src/components/commonV2/dao/DAOConfigEditor.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersTable.tsx
packages/ui_v2/src/components/commonV2/dao/Schemes/AdvancedEditor.tsx

Cotary Create: Step 1 improvements #428

---

packages/ui_v2/src/assets/logos/dao-logo-gray.svg
packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/commonV2/DAOstackLogo.tsx

This PR is for issue: #371 
I added the daostack as in the screenshot in the meantime.

Cotary Create: add a DAOstack logo in the U.I.

---

packages/ui_v2/src/components/DAOcreatorV2/InstallStep.tsx
packages/ui_v2/src/components/commonV2/dao/Migrator/index.tsx

Cotary Create: Removed copy addresses button

---

packages/ui_v2/src/components/DAOcreatorV2/Review.tsx
packages/ui_v2/src/components/DAOcreatorV2/index.tsx
packages/ui_v2/src/components/commonV2/dao/Members/MembersEditor.tsx

Check comment https://github.com/dOrgTech/DAOcreator/issues/432#issuecomment-590526267

Cotary Create: Load from localstorage bug

---

packages/ui_v2/src/components/commonV2/FormField/index.tsx
packages/ui_v2/src/components/commonV2/dao/DAOConfigEditor.tsx
packages/ui_v2/src/components/commonV2/dao/Schemes/SchemeEditor.tsx
packages/ui_v2/src/components/utils/schemesUtils.ts

Cotary Create: Config names changed

---

packages/ui_v2/src/components/DAOcreatorV2/index.tsx

Cotary Create: Top left options fix

---

packages/ui_v2/src/components/DAOcreatorV2/index.tsx

This pr is for fix this issue: #432

Cotary Create: fix loading bug

---

packages/ui_v2/src/components/DAOcreatorV2/InstallStep.tsx

Closes https://github.com/dOrgTech/DAOcreator/issues/467

Cotary Create: Layout Fix

---

packages/lib/src/forms/dao/GenesisProtocolForm.ts
packages/lib/src/forms/fields/TokenField.ts
packages/lib/src/forms/validators.ts
packages/ui_v2/src/components/DAOcreatorV2/Review.tsx
packages/ui_v2/src/components/commonV2/dao/Schemes/SchemeEditor.tsx
packages/ui_v2/src/components/utils/schemesUtils.ts
yarn.lock

Closes https://github.com/dOrgTech/DAOcreator/issues/466

Cotary Create: Minimize DAO Bounty

---

packages/ui_v2/src/components/commonV2/dao/Members/MembersTable.tsx

Cotary Create: edit and remove member icons should be clickable on hover

---

packages/lib/package.json
packages/ui_v1/package.json
yarn.lock

Fixes https://github.com/dOrgTech/DAOcreator/issues/394

Web3 Upgrade (Fixes Windows Install)

---

packages/lib/src/dependency/arc/src/migration.json

Reverts dOrgTech/DAOcreator#488

Revert "Changing migrations file to update kovan"
